.github/workflows/ci.yml

I didn't think to test the fetch command locally before. The shallow fetch causes the branch to have no history, so it cannot be merged with any other branch.

Documentation automation

---

android/build.gradle
android/gradle.properties
android/local.properties
android/src/main/java/com/klaviyoreactnativesdk/KlaviyoReactNativeSdkModule.kt

These take care of some android build issues on older RN versions.
- Specify kotlin version 1.8 for compat with android sdk
- Avoid using an android 24 API `foreach` method
- Revert react-native dependency to the template syntax, and put in a local.properties file so we can override it for development.

Android kotlin version and min SDK fixes

---

android/local.properties
example/android/app/build.gradle
example/android/app/src/main/java/com/klaviyoreactnativesdkexample/MainApplication.kt
example/android/gradle.properties
example/android/local.properties

A nice way to set company ID from local properties for android. This is minor because it only applies to the example app. 
As I write this I realize it'd be nice to do it for iOS example too, though not sure how.

Add template local.properties file for the example app

---

example/ios/Podfile.lock

As I understand it, the klaviyo RN sdk is installed straight from the parent directory, so this lockfile needs to stay in sync.

Bump example iOS project lockfile

---

.github/workflows/android-ci.yml
.github/workflows/ci.yml
.github/workflows/doc-bot.yml
.github/workflows/ios-ci.yml
README.md

Adds badges for CI to the readme, had to split up the yml files so i could have a badge per platform.
In the release automation PR i will change these so that they are linked to _release_ rather than just the latest merge to master.

Break up CI files so we can get individual badges

---

android/build.gradle
android/local.properties.template
example/android/local.properties.template

I mistakenly thought you could have an initial template of a file, and then gitignore it so that changes are ignored. I guess not, and you have to put in a template file like this instead.
This PR renames the two `local.properties` to `local.properties.template` and adds instructions to copy/rename the file so that local config is indeed untracked.

Remove local.properties from git index

---

android/gradle.properties
example/ios/Podfile.lock
example/package.json
klaviyo-react-native-sdk.podspec
package.json

This fixes a bug with notification display on android. Previously, it was required to initialize the SDK prior to displaying a notification (receiving the FCM message intent). If the developer was initializing from react native code only, then initialize did not happen in time, which prevented notification from displaying. This would only happen if the application was in a terminal state.
This android version bump included a fix to remove notification display's dependency upon `initialize`.
- NO
- YES
- Bump to Klaviyo Android version 2.1.1
- With test app, kill the app and reboot your device. 
- Send a notification from klaviyo
- Notification should pop up (previously, it wouldn't appear, and you could see an error in the logcat)
- Has not been reported
- CHNL-6476

Bump to Klaviyo Native SDK Dependencies: Android=2.1.1 Swift=3.0.4 | RN SDK = 0.3.0

---

example/ios/KlaviyoReactNativeSdkExample/AppDelegate.mm
example/ios/KlaviyoReactNativeSdkExample/PushNotificationsHelper.swift

Added sample code in the iOS Example app to demonstrate decrementing badge count.

Updated example app to demo decrementing badge count

---

android/gradle.properties
example/Gemfile
example/Gemfile.lock
example/ios/Podfile.lock
example/package.json
package.json

Adopts recently released Klaviyo Android SDK version 2.2.0 and 
Increment React Native to 0.3.1
- NO
- YES
Version 2.2.0 of the Klaviyo Android SDK added new logic to the networking layer to reduce redundant API calls while also extending retry logic to better retain data during a period of high traffic for a particular company. 
- Unit tests, integration tests and device testing have been performed on the Android SDK and internal test apps.

Adopt Android SDK version 2.2.1

---

ios/KlaviyoBridge.swift
src/Profile.ts

iOS SDK does not use enums for profile identifiers `external_id`, `email` and `phone_number` and isn't intended to consume identifiers with `setProfileAttribute`. Since RN is exposing those enums cross-platform, it is reasonable a developer could expect to set identifiers with that method. But we discovered that could lead to an iOS issue with identifiers not getting tracked in internal state when set via `setProfileAttribute`, though the identifier still makes it to the backend for that profile. 
To resolve this confusion, we're deprecating these enums on android and RN to discourage setting identifiers via the attribute setter method. In a future release we will delete them entirely, but in the mean time updated the bridging behavior to direct any identifiers set with these profile keys …

Patch for profile key enums mismatching

---

src/Profile.ts

Following #143, remove the deprecated keys
- Yes, this should be merged for a subsequent release, after #143 has been released on its own.
- No, this should get merged by or before major version 1.0.
- Remove profile keys corresponding to identifiers.
Confirmed that with the deletion, you can't call `setProfileAttribute` with identifier keys, unless you go out of your way to use a custom key with a value like `"email"`. Even then, I kept the little patch in the swift bridge code from the previous PR, so that would still get routed to the explicit setter on iOS like it does on Android. 
#143 
CHNL-6998

Remove deprecated profile identifier keys

---

src/Profile.ts
src/Push.ts
src/index.tsx

In TypeScript, `string` is a primitive type, while `String` is a global object that is a wrapper around the primitive `string` type. We were using both of these interchangeably which could lead to issues like this - 
```
let existingEmail = Klaviyo.getEmail(undefined);
Klaviyo.setProfile({
email: existingEmail, //this is an error: TS2322: Type String | null is not assignable to type string | undefined
});
```
The above error is because `getEmail` returns an instance of type `String` whereas `setProfile` accepts an instance of `Profile` whose email property is of type `string`.
The fix was to across the board using `string` instead of `String`. This in some cases could be a breaking change if developer made any provision in their code to handle this inconsistency. Since we are in beta we …

Updated occurrences of `String` to `string`

---

README.md

Setting lat and long on a profile doesn't impact the location of the profile on Klaviyo. Hence updated the example to use location properties that do impact the location if a developer was looking to set a user's location.

Update README.md to use appropriate location fields

---

example/ios/KlaviyoReactNativeSdkExample.xcodeproj/project.pbxproj
example/ios/KlaviyoReactNativeSdkExample/AppDelegate.mm
example/ios/Podfile
example/ios/Podfile.lock
example/ios/PrivacyInfo.xcprivacy
yarn.lock

Pulling in the changes made on iOS for modularization. More comments in line.

Adopting modularization work

---

.github/workflows/ios-ci.yml
README.md
android/gradle.properties
example/ios/Podfile
example/ios/Podfile.lock
ios/KlaviyoBridge.swift
klaviyo-react-native-sdk.podspec
package.json

This updates the KlaviyoBridge class to account for the changes made to `EventName` as part of [Swift SDK #196](https://github.com/klaviyo/klaviyo-swift-sdk/pull/196)

[CHNL-6170] updated EventName cases in KlaviyoBridge

---

README.md
Troubleshooting.md

There's a change (issue?) in the react native firebase SDK we use where the push token from APNS is coming back as all caps, where the APNS API is not returning it in this format. This is just an added warning to the readme that describes the issue. 
- updated readme
- 
CHNL-10057
https://github.com/invertase/react-native-firebase/issues/8022

CHNL-10057 Note react native firebase sdk capitalization issue

---

android/src/main/res/values/strings.xml

By adding a manifest resource to the SDK, we can reflect in our Android Repo and check if these values exist, which tells our API the user is sending events through react-native and not android native SDK.
- adding a new string resource folder for sdk name and version
- tested with both the android and react example apps to see if the config was properly set, also updated a test to accommodate for the new error logging if the app context is not initialized
CHNL-12052
An important note about this is that technically a react-native SDK user could override this value and throw off our klaviyo config. Maybe we should add this to the README?

[CHNL-12052] Update to include SDK name and version for Android devices

---

README.md
android/gradle.properties
android/src/main/res/values/strings.xml
example/Gemfile.lock
example/ios/Podfile
example/ios/Podfile.lock
klaviyo-react-native-sdk.podspec
package.json

What's done so far, 
* Pulled in the latest release of the iOS swift SDK - 4.0.0 
* Updated the example iOS app and built it successfully locally. 
* Updated readme to remove beta references 
* Updated readme to indicate no support for expo atm but coming later. 
What's pending?
* Once android SDK is updated, set `KlaviyoReactNativeSdk_klaviyoAndroidSdkVersion` in android/gradle.properties
* Build the local example android app 
* Merge this PR and release.

React native 1.0.0 release branch 

---

.editorconfig

This PR modifies the editorconfig to set the indent size to 4 for Swift & Objc file types, to reflect code style conventions

set editorconfig settings for Swift & objc files

---

.github/workflows/android-build.yml
.github/workflows/android-ci.yml
.github/workflows/ci.yml
.github/workflows/doc-bot.yml
.github/workflows/ios-build.yml
.github/workflows/ios-ci.yml
.github/workflows/publish-sdk.yml
.github/workflows/stale.yml
example/ios/Podfile.lock
example/package.json
package.json
yarn.lock

Updates to CI prior to version 1.2.0 release. Whenever we merge this, I will update the required CI checks for the protected branches in the repo.
- Restored iOS build to CI
- Added a new/old architecture split for both platforms
- Updated our runners’ OS/xcode versions while we're here.
I ran these commands locally to confirm that the arch flags are being obeyed. The caches are the wildcard, but I've set it up so that the cache keys are isolated by architecture so there should be no interference. 
Reviewers can confirm by going in to the latest actions' logs and confirming the pod install and gradle build logs show the new arch flags. 
https://klaviyo.atlassian.net/browse/CHNL-18510 and blockers.

CI Updates

---

android/gradle.properties
android/src/main/res/values/strings.xml
example/ios/Podfile.lock
ios/klaviyo-sdk-configuration.plist
klaviyo-react-native-sdk.podspec
package.json
yarn.lock

Bumping to 1.2.0 for IAF release
Pointing to [4.2.1](https://github.com/klaviyo/klaviyo-swift-sdk/releases/tag/4.2.1) on iOS and [3.3.0](https://github.com/klaviyo/klaviyo-android-sdk/releases/tag/3.3.0) on Android

RN 1.2.0 | Swift 4.2.1 | Android 3.3.0

---

README.md

https://klaviyo.atlassian.net/browse/CHNL-16763
Read the formatted README [here](https://github.com/klaviyo/klaviyo-react-native-sdk/tree/bl/IAF-readme?tab=readme-ov-file#in-app-forms)

Add In-App Forms to README

---

android/gradle.properties
android/src/main/java/com/klaviyoreactnativesdk/KlaviyoReactNativeSdkModule.kt

Relies on an [Android PR](https://github.com/klaviyo/klaviyo-android-sdk/pull/248) that turned currentActivity into a var.
Can be tested locally with
```
KlaviyoReactNativeSdk_klaviyoAndroidSdkVersion=ecm~current-activity-setter-SNAPSHOT
```
I will include the bump to android v 3.3.1 here before merging, just isn't released yet.

Pass along the current activity from react SDK to Android SDK.

---

.github/workflows/ci.yml
.husky/pre-commit
.husky/prepare-commit-msg
package.json
yarn.lock

One reason CI is failing (aside from half the internet being down) is that a yarn package got updated in this branch without the lockfile being committed. In CI, we run `yarn install --immutable` so it'll throw if anything deviates from the lockfile.
This should unblock the rel/1.3.0 branch's CI, and the PR's branched off it.

Chore | Yarn lockfile

---

android/build.gradle
android/gradle.properties
android/local.properties.template
android/settings.gradle
bump-version.sh
configure-sdk.sh
example/android/gradle.properties
example/android/local.properties.template
example/android/settings.gradle

Added some scripts to make local setup and release prep easier.
- If so, please merge to a feature branch so documentation updates only go live upon official release.
- If no, author or reviewer should account for this in a release plan, or describe why not below.
Scripts:
- `bump-version.sh` walks you through updating version numbers prior to a release, built off our [confluence docs](https://klaviyo.atlassian.net/wiki/spaces/EN/pages/4032725175/React+Native+SDK+Release+Guide).
- `configure-sdk.sh` configures native SDK dependencies, to choose between a local copy, a git branch/commit, or an official release, on each platform, built from our [confluence docs](https://klaviyo.atlassian.net/wiki/spaces/EN/pages/3960799590/React+Native+Setup).
Additionally, fixed targeting a local android …

Utils | Added configure-sdk and bump-version scripts

---

android/src/main/java/com/klaviyoreactnativesdk/KlaviyoReactNativeSdkModule.kt

ProfileKey class now has a companion object inside, which broke our constants extractor. This fixes it so that we're filtering down by type <ProfileKey>

IAF | Android constants fix

---

package.json

Addresses the issue [here](https://github.com/klaviyo/klaviyo-react-native-sdk/issues/212) where the new architecture support broke imports for the original RN module resolution method (node). This fix explicitly defines the types older RN projects expect. This is additive to the existing support to the modern module resolution methods (like bundler, that our project and example uses).
- If so, please merge to a feature branch so documentation updates only go live upon official release.
- If no, author or reviewer should account for this in a release plan, or describe why not below.
- Adds backwards support for older moduleResolution
I recreated the error on a starter project by setting the `"moduleResolution": "node"` 
and `npm install klaviyo-react-native-sdk` (version 2.0.1) -- when I …

Backwards compatible module resolution

---

android/gradle.properties
example/ios/Podfile

In order to get CI to run while we do dev work for Universal Links, we need to point the React Native SDK to consume unpublished versions of the iOS and Android SDKs. This is a temporary change that should be reverted before merging this feature branch into `master`.

Consume universal links branches of mobile SDKs

---

.github/workflows/ios-build.yml
android/src/main/res/values/strings.xml
example/ios/Podfile
example/ios/Podfile.lock
ios/klaviyo-sdk-configuration.plist
klaviyo-react-native-sdk.podspec
package.json

This PR bumps React Native SDK 1.2.0 to version 1.2.1, and tells the RN SDK to consume [version 4.2.2](https://github.com/klaviyo/klaviyo-swift-sdk/releases/tag/4.2.2) of the Swift SDK. The Swift update fixes an issue on iOS 26 devices in which an in-app form could get opened in another app.
https://klaviyo.atlassian.net/browse/CHNL-25664
- If so, please merge to a feature branch so documentation updates only go live upon official release.
- If no, author or reviewer should account for this in a release plan, or describe why not below.

Consume Swift SDK v4.2.2

---

android/src/main/java/com/klaviyoreactnativesdk/KlaviyoDeepLinkEventEmitter.kt
android/src/main/java/com/klaviyoreactnativesdk/KlaviyoReactNativeSdkModule.kt
android/src/main/java/com/klaviyoreactnativesdk/KlaviyoReactNativeSdkPackage.kt
example/android/app/src/main/AndroidManifest.xml
example/android/gradle.properties
example/src/App.tsx
src/Event.ts
src/KlaviyoDeepLinkAPI.ts
src/__tests__/index.test.tsx
src/index.tsx

Following up on #260, this PR implements the Android part of the deep link handler. Se the description on that PR for greater detail.
https://klaviyo.atlassian.net/browse/CHNL-24362
- If so, please merge to a feature branch so documentation updates only go live upon official release.
- If no, author or reviewer should account for this in a release plan, or describe why not below.
I registered a deep link handler in the React Native test app, then invoked the deep link via an In-App Form. The GIF below shows an alert being displayed when the deep link is invoked.

[CHNL-24362][Android] wired up Android deep link handler

---

example/ios/KlaviyoReactNativeSdkExample/AppDelegate.mm
example/ios/KlaviyoReactNativeSdkExample/KlaviyoReactNativeSdkExample.entitlements

Added universal links support to the example app by implementing the required iOS delegate method and configuring Associated Domains. This enables the example app to handle universal links.
Also, updated the AASA file with RN SDK example app. Ex - https://trk.theonewhoknocks.work/.well-known/apple-app-site-association
- Example app improvements to demonstrate SDK functionality.
**iOS Universal Links Handler (`AppDelegate.mm`)**
- Added `application:continueUserActivity:restorationHandler:` delegate method (Installation Step 13a)
- Forwards universal links to React Native's `RCTLinkingManager` for handling in JS layer
- Enables HTTPS deep links including Klaviyo universal tracking links
**Associated Domains Configuration (`KlaviyoReactNativeSdkExample.entitlements`)**
- Added …

RN | example app | Universal linking
